const tutors = [
    { email: 'pieter.vdm@example.com', full_name: 'Pieter van der Merwe', subjects: 'Mathematics,Economics', grade_levels: '10,11,12', hourly_rate: 360, experience_years: 10, qualification: 'BCom Accounting - University of Pretoria', bio: 'Chartered Accountant with a passion for education. I make financial concepts intuitive and practical.' },
    { email: 'claire.bio@example.com', full_name: 'Claire Evans', subjects: 'Life Sciences', grade_levels: '10,11,12', hourly_rate: 228, experience_years: 9, qualification: 'BSc Genetics - Wits University', bio: 'I help matric students master biology and excel in their finals. From DNA to human anatomy, I make it simple.' },
    { email: 'sadiaislampromi@gmail.com', full_name: 'Sadia Islam Promi', subjects: 'Mathematics,Business Studies,Economics', grade_levels: '8,9,10,11,12', hourly_rate: 245, experience_years: 13, qualification: 'Masters in Business Administration', bio: 'I enjoy helping students move from confusion to confidence. Tutoring is about understanding how each student learns.' },
    { email: 'amina.lit@example.com', full_name: 'Amina Patel', subjects: 'Mathematical Literacy,Life Orientation', grade_levels: '10,11,12', hourly_rate: 180, experience_years: 6, qualification: 'BEd Foundation Phase - UNISA', bio: 'Patience is my superpower. I help students who struggle with maths build confidence step by step.' },
    { email: 'naledi.eng@example.com', full_name: 'Naledi Chauke', subjects: 'English,History', grade_levels: '8,9,10', hourly_rate: 216, experience_years: 7, qualification: 'BA English - Wits', bio: 'Experienced English teacher. I focus on essay writing skills and literature analysis to help you reach the top.' },
    { email: 'zanele.zulu@example.com', full_name: 'Zanele Khumalo', subjects: 'isiZulu,Life Orientation', grade_levels: '8,9,10', hourly_rate: 192, experience_years: 5, qualification: 'BEd - UKZN', bio: 'Native isiZulu speaker and qualified educator. Sawubona! Let\'s learn together and master the language.' },
    { email: 'johan.afr@example.com', full_name: 'Johan Steyn', subjects: 'Afrikaans,History', grade_levels: '8,9,10,11,12', hourly_rate: 204, experience_years: 8, qualification: 'BA Languages - NWU', bio: 'Moenie stres nie! I make learning Afrikaans grammar and vocabulary engaging and effective.' },
    { email: 'amith.pattar@gmail.com', full_name: 'Amith Pattar', subjects: 'Mathematics,Physical Sciences', grade_levels: '7,8,9,10,11,12', hourly_rate: 325, experience_years: 5, qualification: 'Bachelor’s Degree in Electrical and Electronics Engineering', bio: 'I focus on making learning interactive, engaging, and easy to follow. My goal is to build independent problem-solving skills.' },
    { email: 'suhail.malik@gmail.com', full_name: 'Suhail Gul Malik', subjects: 'Mathematics,English,Economics', grade_levels: '8,9,10', hourly_rate: 250, experience_years: 5, qualification: 'Post Graduation in Economics - Central University of Kashmir', bio: 'I enjoy helping others understand and succeed in their work. I believe in encouraging confidence, patience, and a positive attitude.' },
    { email: 'thembelihlemngoma@gmail.com', full_name: 'Thembelihle Mngoma', subjects: 'isiZulu', grade_levels: '8,9,10,11,12', hourly_rate: 300, experience_years: 5, qualification: 'Online Teaching Certificate', bio: 'I am passionate about isiZulu and want to reach more students who need support in the subject. Conceptual clarity is key.' },
    { email: 'tundecourse@gmail.com', full_name: 'Babatunde Olalekan', subjects: 'English,Mathematics,Other', grade_levels: '8,9,10,11,12', hourly_rate: 700, experience_years: 3, qualification: 'BSc. English', bio: 'Achieving tangible results through personalized mentorship and high-quality resources. English, Maths and Religious studies specialist.' },
    { email: 'wael-fouda@hotmail.com', full_name: 'Wael Hazem Fouda', subjects: 'Information Technology,Computer Applications Technology,Other', grade_levels: '8,9,10,11,12', hourly_rate: 370, experience_years: 5, qualification: 'Bachelor\'s Degree', bio: 'I teach traders to see the market through an institutional lens. Specialized in Technical Analysis, AI/ML for Trading, and Data Science.' },
    { email: 'Mcanthonyigwe@gmail.com', full_name: 'Mcanthony Igwe', subjects: 'Mathematics,Other', grade_levels: '8,9,10,11,12', hourly_rate: 250, experience_years: 2, qualification: 'BSc computer science Eduvos University', bio: 'I enjoy breaking complex ideas in mathematics and chess into recognizable and digestible patterns.' },
    { email: 'soniarao473@gmail.com', full_name: 'Sonia Rao', subjects: 'Mathematics', grade_levels: '4,5,6,7,8', hourly_rate: 555, experience_years: 9, qualification: 'Masters in Mathematics', bio: 'I try to explain mathematical concepts step by step so students can learn easily. My goal is to develop problem-solving abilities.' }
];

module.exports = tutors;
