const tutors = [
    { email: 'sadiaislampromi@gmail.com', full_name: 'Sadia Islam Promi', subjects: 'Mathematics,Business Studies,Economics', grade_levels: '8,9,10,11,12', hourly_rate: 245, experience_years: 13, qualification: 'Masters in Business Administration', bio: 'I am passionate about teaching because I enjoy helping students move from confusion to confidence. Tutoring is about understanding how each student learns.' },
    { email: 'amith.pattar@gmail.com', full_name: 'Amith Pattar', subjects: 'Mathematics,Physical Sciences', grade_levels: '7,8,9,10,11,12', hourly_rate: 325, experience_years: 5, qualification: 'Bachelor’s Degree in Electrical and Electronics Engineering', bio: 'I focus on making learning interactive, engaging, and easy to follow. My goal is to build independent problem-solving skills.' },
    { email: 'suhail.malik@gmail.com', full_name: 'Suhail Gul Malik', subjects: 'Mathematics,English,Economics', grade_levels: '8,9,10', hourly_rate: 250, experience_years: 5, qualification: 'Post Graduation in Economics - Central University of Kashmir', bio: 'I enjoy helping others understand and succeed in their work. I believe in encouraging confidence, patience, and a positive attitude.' },
    { email: 'thembelihlemngoma@gmail.com', full_name: 'Thembelihle Mngoma', subjects: 'isiZulu', grade_levels: '8,9,10,11,12', hourly_rate: 300, experience_years: 5, qualification: 'Online Teaching Certificate', bio: 'I am passionate about isiZulu and want to reach more students who need support in the subject. Conceptual clarity is key.' },
    { email: 'tundecourse@gmail.com', full_name: 'Babatunde Olalekan', subjects: 'English,Mathematics,Other', grade_levels: '8,9,10,11,12', hourly_rate: 700, experience_years: 3, qualification: 'BSc. English', bio: 'Achieving tangible results through personalized mentorship and high-quality resources. English, Maths and Religious studies specialist.' },
    { email: 'wael-fouda@hotmail.com', full_name: 'Wael Hazem Fouda', subjects: 'Information Technology,Computer Applications Technology,Other', grade_levels: '8,9,10,11,12', hourly_rate: 370, experience_years: 5, qualification: 'Bachelor\'s Degree', bio: 'I teach traders to see the market through an institutional lens. Specialized in Technical Analysis, AI/ML for Trading, and Data Science.' },
    { email: 'Mcanthonyigwe@gmail.com', full_name: 'Mcanthony Igwe', subjects: 'Mathematics,Other', grade_levels: '8,9,10,11,12', hourly_rate: 250, experience_years: 2, qualification: 'BSc computer science Eduvos University', bio: 'I enjoy breaking complex ideas in mathematics and chess into recognizable and digestible patterns.' },
    { email: 'soniarao473@gmail.com', full_name: 'Sonia Rao', subjects: 'Mathematics', grade_levels: '4,5,6,7,8', hourly_rate: 555, experience_years: 9, qualification: 'Masters in Mathematics', bio: 'I try to explain mathematical concepts step by step so students can learn easily. My goal is to develop problem-solving abilities.' },
    { email: 'mathstatlablessons@gmail.com', full_name: 'Justus Mwanthi', subjects: 'Mathematics,Statistics,Other', grade_levels: '8,10,11,12,Other', hourly_rate: 215, experience_years: 6, qualification: 'BSc (Pure Mathematics, Applied Mathematics, and Statistics) – Kisii University', bio: 'I am Justus Mwanthi, a mathematics and statistics tutor with more than six years of experience teaching students from middle school to postgraduate level. I specialize in simplifying difficult concepts and guiding students step by step until they fully understand the work.' },
    { email: 'courtney.stuart@example.com', full_name: 'Courtney Stuart', subjects: 'English', grade_levels: '8,9,10,11,12', hourly_rate: 110, experience_years: 6, qualification: 'National Diploma in Early Childhood Development- ATS', bio: 'Hello there! I am Courtney, a tutor with over 6 years experience being an educator. I believe lessons should have an engaging element such as games...' }
];

module.exports = tutors;
